cwd := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
env_file := $(cwd)/.env
ssh_conf_path := ${HOME}/.ssh/tf-worker

tf_approve_opts = --auto-approve
TF_VAR_aws_access_key = ${AWS_ACCESS_KEY_ID}
TF_VAR_aws_secret_key = ${AWS_SECRET_ACCESS_KEY}

ifneq ("$(wildcard $(env_file))","")
	include $(env_file)
	export
endif

wrap_targets := terraform tf out
ifneq ($(filter $(firstword $(MAKECMDGOALS)), $(wrap_targets)), )
  RUN_ARGS := $(wordlist 2, $(words $(MAKECMDGOALS)), $(MAKECMDGOALS))
  $(eval $(RUN_ARGS):;@:)
endif

all: init apply ssh-config ssh
	@echo Done!
	@echo Please run: 'eval $$(make config)'

env:
	@env

version:
	terraform --version

config:
	@echo export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
	@echo export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

init:
	terraform init

plan:
	terraform plan

apply:
	terraform apply ${tf_approve_opts}

destroy:
	terraform destroy ${tf_approve_opts}

output:
	terraform output

out:
	@terraform output -raw $(RUN_ARGS)

ssh-config:
	$(eval host_ip = $(shell terraform output host_ip))

	@echo '# Generated by tf-worker' > $(ssh_conf_path) &&\
	echo Host $(host_ip) >> ${ssh_conf_path} &&\
  echo '  SendEnv AWS_ACCESS_KEY_ID' >> ${ssh_conf_path} &&\
  echo '  SendEnv AWS_SECRET_ACCESS_KEY' >> ${ssh_conf_path}

ssh:
	@export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
	@export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

	$(eval host = $(shell terraform output ssh_connection))
	ssh -A -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t $(host) # "cd /tmp; sudo bash"
